[package]
authors = ["Austin Hellyer <hello@austinhellyer.me>"]
build = "build.rs"
name = "kitsu_io"
version = "0.1.0"

[dependencies]
hyper = "0.9"
serde = "0.8"
serde_json = "0.8"

[build-dependencies]
serde_codegen = "0.8"
